BEGIN;

DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE IF NOT EXISTS "user" (
  "id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "password" TEXT NOT NULL,
  "isAdmin" BOOLEAN DEFAULT FALSE,
  "avatar" TEXT,
  "phone" INT,
  "verified" BOOLEAN DEFAULT FALSE
);


COMMIT;
